---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |
    .:53 {
        etcd example.com. {
          stubzones
          path /skydns
          endpoint https://coredns-etcd.federation:2379
          tls /etc/etcd/client.pem /etc/etcd/client-key.pem /etc/etcd/ca.pem
        }
        errors stdout
        log stdout
        loadbalance round_robin
        health
        proxy . /etc/resolv.conf
        cache 30
    }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coredns
  labels:
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: coredns
  template:
    metadata:
      labels:
        k8s-app: coredns
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: coredns
        image: coredns/coredns:latest
        imagePullPolicy: Always
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        - name: etcd-client
          mountPath: /etc/etcd
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
        - name: etcd-client
          secret:
            secretName: etcd-client
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
 
---
apiVersion: v1
kind: Service
metadata:
  name: coredns
  labels:
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "coredns"
spec:
  selector:
    k8s-app: coredns
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP

